username=""
password=""
VAGRANT_BOX         = "generic/rhel9"
VAGRANT_BOX_VERSION = "4.3.12"
CPUS_MASTER_NODE    = 2
CPUS_WORKER_NODE    = 2
MEMORY_MASTER_NODE  = 2048
MEMORY_WORKER_NODE  = 2048
WORKER_NODES_COUNT  = 2

Vagrant.configure(2) do |config|
    nexusCount=1
    (1..nexusCount).each do |i|
  
      config.vm.define "nexus" do |masternode|
        masternode.vm.provision "file", source: "/root/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
        masternode.vm.provision "shell", inline: <<-SHELL
          cat /home/vagrant/.ssh/me.pub >> /root/.ssh/authorized_keys
        SHELL
        masternode.vm.box               = VAGRANT_BOX
        masternode.vm.box_check_update  = false
        masternode.vm.box_version       = VAGRANT_BOX_VERSION
        masternode.vm.hostname          = "nexus"
  
        masternode.vm.network "private_network", ip: "172.16.16.215"
        masternode.vm.network "forwarded_port", guest: 8081, host: 8081
       
        masternode.vm.provider :libvirt do |v|
          v.nested  = true
          v.memory  = 4096
          v.cpus    = 4
        end
        
      
    end
end
       
end
